# Generated by Django 5.2.8 on 2025-11-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='NA', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
