# Generated by Django 5.2.8 on 2025-11-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
